#!/usr/bin/env python3
"""Generate deterministic synthetic fixtures for offline pipeline runs.

These are SYNTHETIC. They are shaped like Massive aggregate bars so the envelope,
validators and manifest can be exercised without network access, and they are
deliberately not real prices -- committing real market data as a test fixture
invites someone downstream to treat it as a source.

The ticker list and each ticker's price series are both derived from
tickers.json. That is deliberate, and it replaced a hand-maintained seed table:

  - Adding a ticker is a one-place edit. With a separate seed table, adding a
    ticker meant editing two files, and forgetting the second made --source
    fixture fail with a hard SystemExit.
  - Fixture content depends only on the symbol, so two people adding NVDA
    independently get byte-identical data. With hand-picked seeds they did not --
    five independent runs of that task produced two different NVDA datasets,
    which makes "the fixtures are reproducible" an unverifiable claim.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
FIXTURE_DIR = SKILL_DIR / "fixtures"
CONFIG_PATH = SKILL_DIR / "tickers.json"
DAY_MS = 86_400_000
EPOCH_START = 1_767_225_600_000  # 2026-01-01T00:00:00Z
BAR_COUNT = 120


def series_params(ticker: str) -> tuple[float, int]:
    """Derive (base price, phase seed) from the symbol alone.

    Any function of the symbol would do; what matters is that it is a pure
    function, so the fixture for a symbol is the same for everyone forever.
    """
    digest = hashlib.sha256(ticker.encode()).hexdigest()
    base = 50.0 + (int(digest[:8], 16) % 20_000) / 100.0  # 50.00 - 250.00
    seed = int(digest[8:12], 16) % 97 + 1
    return round(base, 2), seed


def build_bars(base: float, seed: int, count: int = BAR_COUNT) -> list[dict]:
    bars = []
    for i in range(count):
        drift = math.sin((i + seed) / 9.0) * (base * 0.04)
        open_ = round(base + drift, 2)
        close = round(open_ + math.cos((i + seed) / 7.0) * (base * 0.015), 2)
        high = round(max(open_, close) + base * 0.008, 2)
        low = round(min(open_, close) - base * 0.008, 2)
        bars.append(
            {
                "t": EPOCH_START + i * DAY_MS,
                "o": open_,
                "h": high,
                "l": low,
                "c": close,
                "v": float(1_000_000 + ((i * seed * 7919) % 500_000)),
            }
        )
    return bars


def main() -> None:
    config = json.loads(CONFIG_PATH.read_text())
    tickers = config["tickers"]
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)

    wanted = set()
    for ticker in sorted(tickers):
        base, seed = series_params(ticker)
        payload = {
            "_synthetic": True,
            "_note": "Generated by make_fixtures.py from the symbol. Not real market data. Do not cite.",
            "ticker": ticker,
            "bars": build_bars(base, seed),
        }
        path = FIXTURE_DIR / f"{ticker}.json"
        path.write_text(json.dumps(payload, indent=2) + "\n")
        wanted.add(path.name)
        print(f"wrote fixtures/{ticker}.json  base={base} seed={seed} ({BAR_COUNT} bars)")

    # A fixture for a ticker no longer in the config is dead weight that will
    # confuse the next person debugging a fetch, so say so rather than leaving it.
    orphans = sorted(p.name for p in FIXTURE_DIR.glob("*.json") if p.name not in wanted)
    if orphans:
        print(f"\nnote: {len(orphans)} fixture(s) no longer in tickers.json: {', '.join(orphans)}")
        print("      remove them, or re-add the ticker to the config.")


if __name__ == "__main__":
    main()
