#!/usr/bin/env python3
"""Generate deterministic synthetic fixtures for offline pipeline runs.

These are SYNTHETIC. They are shaped like Massive aggregate bars so the envelope,
validators and manifest can be exercised without network access, and they are
deliberately not real prices -- committing real market data as a test fixture
invites someone downstream to treat it as a source.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures"
DAY_MS = 86_400_000
EPOCH_START = 1_767_225_600_000  # 2026-01-01T00:00:00Z

# Fixed per-ticker seeds keep output byte-identical across runs, so a fixture diff
# in review always means someone changed the generator on purpose.
TICKERS = {"AAPL": (100.0, 7), "AMZN": (150.0, 11), "SHOP": (60.0, 13)}


def build_bars(base: float, seed: int, count: int = 120) -> list[dict]:
    bars = []
    for i in range(count):
        drift = math.sin((i + seed) / 9.0) * (base * 0.04)
        open_ = round(base + drift, 2)
        close = round(open_ + math.cos((i + seed) / 7.0) * (base * 0.015), 2)
        high = round(max(open_, close) + base * 0.008, 2)
        low = round(min(open_, close) - base * 0.008, 2)
        bars.append(
            {
                "t": EPOCH_START + i * DAY_MS,
                "o": open_,
                "h": high,
                "l": low,
                "c": close,
                "v": float(1_000_000 + ((i * seed * 7919) % 500_000)),
            }
        )
    return bars


def main() -> None:
    FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    for ticker, (base, seed) in TICKERS.items():
        payload = {
            "_synthetic": True,
            "_note": "Generated by make_fixtures.py. Not real market data. Do not cite.",
            "ticker": ticker,
            "bars": build_bars(base, seed),
        }
        path = FIXTURE_DIR / f"{ticker}.json"
        path.write_text(json.dumps(payload, indent=2) + "\n")
        print(f"wrote {path.relative_to(Path.cwd())} ({len(payload['bars'])} bars)")


if __name__ == "__main__":
    main()
